"""verifications table

Revision ID: 4cd817a09221
Revises: 0002_fts_vector
Create Date: 2026-05-30 12:53:04.430721
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4cd817a09221'
down_revision: Union[str, None] = '0002_fts_vector'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.String(length=80), nullable=False),
    sa.Column('verifier', sa.String(length=128), nullable=False),
    sa.Column('support_label', sa.String(length=32), nullable=False),
    sa.Column('support_score', sa.Float(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_claim_id'), 'verifications', ['claim_id'], unique=False)
    op.create_index(op.f('ix_verifications_created_at'), 'verifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_verifications_outcome'), 'verifications', ['outcome'], unique=False)
    op.create_index(op.f('ix_verifications_support_label'), 'verifications', ['support_label'], unique=False)
    op.create_index(op.f('ix_verifications_verifier'), 'verifications', ['verifier'], unique=False)
    # NOTE: ix_entities_fts is a functional index managed by hand in 0002 (not in ORM
    # metadata). Autogenerate flagged it for drop; intentionally left untouched here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifications_verifier'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_support_label'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_outcome'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_created_at'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_claim_id'), table_name='verifications')
    op.drop_table('verifications')
    # ### end Alembic commands ###
