"""initial canonical schema

Revision ID: 4e5c94684bcc
Revises: 
Create Date: 2026-05-30 12:41:24.039810
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4e5c94684bcc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('about_kind', sa.String(length=16), nullable=False),
    sa.Column('about_id', sa.String(length=80), nullable=False),
    sa.Column('assertion', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('support_spans', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('disputed', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('generator', sa.String(length=128), nullable=True),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('sensitivity', sa.String(length=16), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('external_id', sa.String(length=256), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_by', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_claim_about', 'claims', ['about_kind', 'about_id'], unique=False)
    op.create_index(op.f('ix_claims_about_id'), 'claims', ['about_id'], unique=False)
    op.create_index(op.f('ix_claims_about_kind'), 'claims', ['about_kind'], unique=False)
    op.create_index(op.f('ix_claims_batch_id'), 'claims', ['batch_id'], unique=False)
    op.create_index(op.f('ix_claims_confidence'), 'claims', ['confidence'], unique=False)
    op.create_index(op.f('ix_claims_disputed'), 'claims', ['disputed'], unique=False)
    op.create_index(op.f('ix_claims_generator'), 'claims', ['generator'], unique=False)
    op.create_index(op.f('ix_claims_recorded_at'), 'claims', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_claims_source_system'), 'claims', ['source_system'], unique=False)
    op.create_index(op.f('ix_claims_superseded_by'), 'claims', ['superseded_by'], unique=False)
    op.create_index(op.f('ix_claims_tier'), 'claims', ['tier'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('subtype', sa.String(length=64), nullable=True),
    sa.Column('label', sa.String(length=512), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.Integer(), nullable=True),
    sa.Column('valid_to', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('generator', sa.String(length=128), nullable=True),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('sensitivity', sa.String(length=16), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('external_id', sa.String(length=256), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_by', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'external_id', name='uq_entity_source_external')
    )
    op.create_index(op.f('ix_entities_batch_id'), 'entities', ['batch_id'], unique=False)
    op.create_index(op.f('ix_entities_generator'), 'entities', ['generator'], unique=False)
    op.create_index(op.f('ix_entities_label'), 'entities', ['label'], unique=False)
    op.create_index(op.f('ix_entities_module'), 'entities', ['module'], unique=False)
    op.create_index(op.f('ix_entities_recorded_at'), 'entities', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_entities_source_system'), 'entities', ['source_system'], unique=False)
    op.create_index(op.f('ix_entities_superseded_by'), 'entities', ['superseded_by'], unique=False)
    op.create_index(op.f('ix_entities_tier'), 'entities', ['tier'], unique=False)
    op.create_index(op.f('ix_entities_type'), 'entities', ['type'], unique=False)
    op.create_index('ix_entity_module_type', 'entities', ['module', 'type'], unique=False)
    op.create_table('external_ids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kid', sa.String(length=80), nullable=False),
    sa.Column('authority', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authority', 'value', name='uq_external_authority_value')
    )
    op.create_index(op.f('ix_external_ids_authority'), 'external_ids', ['authority'], unique=False)
    op.create_index(op.f('ix_external_ids_kid'), 'external_ids', ['kid'], unique=False)
    op.create_index(op.f('ix_external_ids_value'), 'external_ids', ['value'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('citation', sa.String(length=2048), nullable=False),
    sa.Column('uri', sa.String(length=2048), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('external_id', sa.String(length=256), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_source_system'), 'sources', ['source_system'], unique=False)
    op.create_index(op.f('ix_sources_uri'), 'sources', ['uri'], unique=False)
    op.create_table('claim_sources',
    sa.Column('claim_id', sa.String(length=80), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id', 'source_id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('subject_id', sa.String(length=80), nullable=False),
    sa.Column('predicate', sa.String(length=128), nullable=False),
    sa.Column('object_id', sa.String(length=80), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('generator', sa.String(length=128), nullable=True),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('sensitivity', sa.String(length=16), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('external_id', sa.String(length=256), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_by', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'external_id', name='uq_relationship_source_external')
    )
    op.create_index('ix_relationship_triple', 'relationships', ['subject_id', 'predicate', 'object_id'], unique=False)
    op.create_index(op.f('ix_relationships_batch_id'), 'relationships', ['batch_id'], unique=False)
    op.create_index(op.f('ix_relationships_generator'), 'relationships', ['generator'], unique=False)
    op.create_index(op.f('ix_relationships_object_id'), 'relationships', ['object_id'], unique=False)
    op.create_index(op.f('ix_relationships_predicate'), 'relationships', ['predicate'], unique=False)
    op.create_index(op.f('ix_relationships_recorded_at'), 'relationships', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_relationships_source_system'), 'relationships', ['source_system'], unique=False)
    op.create_index(op.f('ix_relationships_subject_id'), 'relationships', ['subject_id'], unique=False)
    op.create_index(op.f('ix_relationships_superseded_by'), 'relationships', ['superseded_by'], unique=False)
    op.create_index(op.f('ix_relationships_tier'), 'relationships', ['tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_tier'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_superseded_by'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_subject_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_system'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_recorded_at'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_predicate'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_object_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_generator'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_batch_id'), table_name='relationships')
    op.drop_index('ix_relationship_triple', table_name='relationships')
    op.drop_table('relationships')
    op.drop_table('claim_sources')
    op.drop_index(op.f('ix_sources_uri'), table_name='sources')
    op.drop_index(op.f('ix_sources_source_system'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_external_ids_value'), table_name='external_ids')
    op.drop_index(op.f('ix_external_ids_kid'), table_name='external_ids')
    op.drop_index(op.f('ix_external_ids_authority'), table_name='external_ids')
    op.drop_table('external_ids')
    op.drop_index('ix_entity_module_type', table_name='entities')
    op.drop_index(op.f('ix_entities_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_tier'), table_name='entities')
    op.drop_index(op.f('ix_entities_superseded_by'), table_name='entities')
    op.drop_index(op.f('ix_entities_source_system'), table_name='entities')
    op.drop_index(op.f('ix_entities_recorded_at'), table_name='entities')
    op.drop_index(op.f('ix_entities_module'), table_name='entities')
    op.drop_index(op.f('ix_entities_label'), table_name='entities')
    op.drop_index(op.f('ix_entities_generator'), table_name='entities')
    op.drop_index(op.f('ix_entities_batch_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_claims_tier'), table_name='claims')
    op.drop_index(op.f('ix_claims_superseded_by'), table_name='claims')
    op.drop_index(op.f('ix_claims_source_system'), table_name='claims')
    op.drop_index(op.f('ix_claims_recorded_at'), table_name='claims')
    op.drop_index(op.f('ix_claims_generator'), table_name='claims')
    op.drop_index(op.f('ix_claims_disputed'), table_name='claims')
    op.drop_index(op.f('ix_claims_confidence'), table_name='claims')
    op.drop_index(op.f('ix_claims_batch_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_about_kind'), table_name='claims')
    op.drop_index(op.f('ix_claims_about_id'), table_name='claims')
    op.drop_index('ix_claim_about', table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
