"""reconciliations table

Revision ID: bc8c0fc807ec
Revises: 4cd817a09221
Create Date: 2026-05-30 14:35:47.850686
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bc8c0fc807ec'
down_revision: Union[str, None] = '4cd817a09221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('left_kid', sa.String(length=80), nullable=False),
    sa.Column('right_kid', sa.String(length=80), nullable=False),
    sa.Column('left_source', sa.String(length=64), nullable=True),
    sa.Column('right_source', sa.String(length=64), nullable=True),
    sa.Column('match_method', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('left_kid', 'right_kid', name='uq_reconciliation_pair')
    )
    op.create_index(op.f('ix_reconciliations_left_kid'), 'reconciliations', ['left_kid'], unique=False)
    op.create_index(op.f('ix_reconciliations_right_kid'), 'reconciliations', ['right_kid'], unique=False)
    op.create_index(op.f('ix_reconciliations_status'), 'reconciliations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliations_status'), table_name='reconciliations')
    op.drop_index(op.f('ix_reconciliations_right_kid'), table_name='reconciliations')
    op.drop_index(op.f('ix_reconciliations_left_kid'), table_name='reconciliations')
    op.drop_table('reconciliations')
    # ### end Alembic commands ###
